(define (problem bagend)
(:domain bagend)
(:objects
    A B C D E F G H I - pomieszczenie
    zielony czerwony pomaranczowy rozowy niebieski - kolor
    k1 k2 k3 k4 k5 - numer
    x1 y1 x2 y2 x3 y3 - wspolrzedne
    1 2 3 4 5 6 7 8  - klocki
)
(:init
    (merry F)
    (zagadka A)
    (przejscie A B pomaranczowy)
    (przejscie A C czerwony)
    (przejscie C A czerwony)
    (przejscie B D pomaranczowy)
    (przejscie C E zielony)
    (przejscie E C zielony)
    (przejscie D F zielony)
    (przejscie F D zielony)
    (przejscie E F niebieski)
    (przejscie F E niebieski)
    (przejscie F G rozowy)
    (przejscie E H czerwony)
    (przejscie H E czerwony)
    (przejscie H I niebieski)
    (przejscie I H niebieski)
    (przejscie F I niebieski)
    (przejscie I F niebieski)
    (kula A zielony k1)
    (kula B rozowy k1)
    (kula C pomaranczowy k1)
    (kula C niebieski k1)
    (kula D zielony k2)
    (kula D czerwony k1)
    (kula E niebieski k2)
    (kula E zielony k3)
    (kula F niebieski k4)
    (kula F niebieski k5)
    (kula H zielony k4)
    (kula H czerwony k2)
    (kula I pomaranczowy k2)
    (kula I niebieski k5)
    (klocek 5 x1 y1)
    (klocek 4 x2 y1)
    (klocek 1 x3 y1)
    (klocek 8 x1 y2)
    (klocek 3 x3 y2)
    (klocek 7 x1 y3)
    (klocek 2 x2 y3)
    (klocek 6 x3 y3)
    (puste x2 y2)
    (sasiad x1 y1 x2 y1)
    (sasiad x2 y1 x1 y1)
    (sasiad x1 y1 x1 y2)
    (sasiad x1 y2 x1 y1)
    (sasiad x1 y2 x2 y2)
    (sasiad x2 y2 x1 y2)
    (sasiad x1 y2 x1 y3)
    (sasiad x1 y3 x1 y2)
    (sasiad x2 y1 x2 y2)
    (sasiad x2 y2 x2 y1)
    (sasiad x2 y2 x2 y3)
    (sasiad x2 y3 x2 y2)
    (sasiad x1 y3 x2 y3)
    (sasiad x2 y1 x3 y1)
    (sasiad x3 y1 x2 y1)
    (sasiad x2 y2 x3 y2)
    (sasiad x3 y2 x2 y2)
    (sasiad x2 y3 x3 y3)
    (sasiad x3 y3 x2 y3)
    (sasiad x3 y1 x3 y2)
    (sasiad x3 y2 x3 y1)
    (sasiad x3 y2 x3 y3)
    (sasiad x3 y3 x3 y2)
)
(:goal (and
    (klocek 1 x1 y1)
    (klocek 2 x2 y1)
    (klocek 3 x3 y1)
    (klocek 4 x1 y2)
    (klocek 5 x2 y2)
    (klocek 6 x3 y2)
    (klocek 7 x1 y3)
    (klocek 8 x2 y3)
    (puste x3 y3)
    (merry G)
    )
)
)
